title: "Project BUDDY"
theme: minima

header_pages:
  - UserGuide.md
  - DeveloperGuide.md
  - AboutUs.md

markdown: kramdown

repository: "AY2122S2-TIC4002-F18-3/tp2"
github_icon: "images/github-icon.png"

plugins:
  - jemoji
